//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CeaIndexer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CeaIndexer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse....
        /// </summary>
        public static string Btn_Browse {
            get {
                return ResourceManager.GetString("Btn_Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Btn_Cancel {
            get {
                return ResourceManager.GetString("Btn_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Btn_Home {
            get {
                return ResourceManager.GetString("Btn_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Settings.
        /// </summary>
        public static string Btn_Save {
            get {
                return ResourceManager.GetString("Btn_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Selection.
        /// </summary>
        public static string Btn_SaveSelection {
            get {
                return ResourceManager.GetString("Btn_SaveSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan File.
        /// </summary>
        public static string Btn_ScanFile {
            get {
                return ResourceManager.GetString("Btn_ScanFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan Folder.
        /// </summary>
        public static string Btn_ScanFolder {
            get {
                return ResourceManager.GetString("Btn_ScanFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search engine.
        /// </summary>
        public static string Btn_SearchEngine {
            get {
                return ResourceManager.GetString("Btn_SearchEngine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Btn_Settings {
            get {
                return ResourceManager.GetString("Btn_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle theme.
        /// </summary>
        public static string Btn_ToggleTheme {
            get {
                return ResourceManager.GetString("Btn_ToggleTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KMB Files (*.cea)|*.cea|All Files (*.*)|*.*.
        /// </summary>
        public static string Dialog_Filter_Cea {
            get {
                return ResourceManager.GetString("Dialog_Filter_Cea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select data files to scan.
        /// </summary>
        public static string Dialog_Title_SelectFiles {
            get {
                return ResourceManager.GetString("Dialog_Title_SelectFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a folder to scan.
        /// </summary>
        public static string Dialog_Title_SelectFolder {
            get {
                return ResourceManager.GetString("Dialog_Title_SelectFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Folder....
        /// </summary>
        public static string FirstRun_AddFolder {
            get {
                return ResourceManager.GetString("FirstRun_AddFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse....
        /// </summary>
        public static string FirstRun_Browse {
            get {
                return ResourceManager.GetString("FirstRun_Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Before we begin, let’s go over the basic settings. You can change these settings at any time later..
        /// </summary>
        public static string FirstRun_Description {
            get {
                return ResourceManager.GetString("FirstRun_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path to the erx.exe program:.
        /// </summary>
        public static string FirstRun_ErxPath {
            get {
                return ResourceManager.GetString("FirstRun_ErxPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source data files (.cea):.
        /// </summary>
        public static string FirstRun_Folders {
            get {
                return ResourceManager.GetString("FirstRun_Folders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to the app!.
        /// </summary>
        public static string FirstRun_Header {
            get {
                return ResourceManager.GetString("FirstRun_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czech (cs-CZ).
        /// </summary>
        public static string FirstRun_LangCs {
            get {
                return ResourceManager.GetString("FirstRun_LangCs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English (en-US).
        /// </summary>
        public static string FirstRun_LangEn {
            get {
                return ResourceManager.GetString("FirstRun_LangEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language:.
        /// </summary>
        public static string FirstRun_Language {
            get {
                return ResourceManager.GetString("FirstRun_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove folder.
        /// </summary>
        public static string FirstRun_RemoveFolder {
            get {
                return ResourceManager.GetString("FirstRun_RemoveFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save and continue.
        /// </summary>
        public static string FirstRun_Save {
            get {
                return ResourceManager.GetString("FirstRun_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string FirstRun_Title {
            get {
                return ResourceManager.GetString("FirstRun_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear selection.
        /// </summary>
        public static string Indexer_DeselectAll {
            get {
                return ResourceManager.GetString("Indexer_DeselectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All.
        /// </summary>
        public static string Indexer_SelectAll {
            get {
                return ResourceManager.GetString("Indexer_SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Indexing.
        /// </summary>
        public static string Indexer_StartButton {
            get {
                return ResourceManager.GetString("Indexer_StartButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indexing new data.
        /// </summary>
        public static string Indexer_Title {
            get {
                return ResourceManager.GetString("Indexer_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to the main overview.
        /// </summary>
        public static string IndexerView_BackMessage {
            get {
                return ResourceManager.GetString("IndexerView_BackMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go back.
        /// </summary>
        public static string IndexerView_BackTitle {
            get {
                return ResourceManager.GetString("IndexerView_BackTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🎉 All done! A total of {0} measure points from {1} files have been saved..
        /// </summary>
        public static string IndexerView_CompleteMessage {
            get {
                return ResourceManager.GetString("IndexerView_CompleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string IndexerView_ErrorTitle {
            get {
                return ResourceManager.GetString("IndexerView_ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatal scanner error: {0}.
        /// </summary>
        public static string IndexerView_FatalScannerErrorPrefix {
            get {
                return ResourceManager.GetString("IndexerView_FatalScannerErrorPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error:.
        /// </summary>
        public static string IndexerView_FileErrorPrefix {
            get {
                return ResourceManager.GetString("IndexerView_FileErrorPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devices found: {0}.
        /// </summary>
        public static string IndexerView_FoundDevicesInfo {
            get {
                return ResourceManager.GetString("IndexerView_FoundDevicesInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have not selected any files to index..
        /// </summary>
        public static string IndexerView_NoFilesSelected {
            get {
                return ResourceManager.GetString("IndexerView_NoFilesSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} of {1} files processed ({2} %).
        /// </summary>
        public static string IndexerView_ProcessingProgress {
            get {
                return ResourceManager.GetString("IndexerView_ProcessingProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0 of {0} files processed (0%).
        /// </summary>
        public static string IndexerView_ProcessingZero {
            get {
                return ResourceManager.GetString("IndexerView_ProcessingZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantities: {0} | Archives: {1}.
        /// </summary>
        public static string IndexerView_QuantitiesAndArchivesInfo {
            get {
                return ResourceManager.GetString("IndexerView_QuantitiesAndArchivesInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching for Measure Points....
        /// </summary>
        public static string IndexerView_SearchingMeasurePoints {
            get {
                return ResourceManager.GetString("IndexerView_SearchingMeasurePoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czech (cs-CZ).
        /// </summary>
        public static string Lang_Cs {
            get {
                return ResourceManager.GetString("Lang_Cs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English (en-US).
        /// </summary>
        public static string Lang_En {
            get {
                return ResourceManager.GetString("Lang_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERX Explorer.
        /// </summary>
        public static string MainWindow_Subtitle {
            get {
                return ResourceManager.GetString("MainWindow_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERX Data Catalog.
        /// </summary>
        public static string MainWindow_Title {
            get {
                return ResourceManager.GetString("MainWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string Msg_Done {
            get {
                return ResourceManager.GetString("Msg_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Msg_ErrorTitle {
            get {
                return ResourceManager.GetString("Msg_ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing Configuration.
        /// </summary>
        public static string Msg_MissingSettingsTitle {
            get {
                return ResourceManager.GetString("Msg_MissingSettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred during scanning:.
        /// </summary>
        public static string Msg_ScanError {
            get {
                return ResourceManager.GetString("Msg_ScanError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file/s was/were successfully scanned and saved to the database!.
        /// </summary>
        public static string Msg_ScanSuccess {
            get {
                return ResourceManager.GetString("Msg_ScanSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently Processing:.
        /// </summary>
        public static string Progress_CurrentlyProcessing {
            get {
                return ResourceManager.GetString("Progress_CurrentlyProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Queue.
        /// </summary>
        public static string Progress_FileQueue {
            get {
                return ResourceManager.GetString("Progress_FileQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparing to scan....
        /// </summary>
        public static string Progress_Preparing {
            get {
                return ResourceManager.GetString("Progress_Preparing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Indexing Monitoring.
        /// </summary>
        public static string Progress_Title {
            get {
                return ResourceManager.GetString("Progress_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The files are currently being scanned. Please wait until the process is complete..
        /// </summary>
        public static string ProgressWindow_ScanningInProgressMessage {
            get {
                return ResourceManager.GetString("ProgressWindow_ScanningInProgressMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanning in progress.
        /// </summary>
        public static string ProgressWindow_ScanningInProgressTitle {
            get {
                return ResourceManager.GetString("ProgressWindow_ScanningInProgressTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a file from the list on the left....
        /// </summary>
        public static string ProgressWindow_SelectFile {
            get {
                return ResourceManager.GetString("ProgressWindow_SelectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queued for processing....
        /// </summary>
        public static string ProgressWindow_WaitingForProcessing {
            get {
                return ResourceManager.GetString("ProgressWindow_WaitingForProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Folder.
        /// </summary>
        public static string Settings_AddFolder {
            get {
                return ResourceManager.GetString("Settings_AddFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path to the erx.exe program.
        /// </summary>
        public static string Settings_ErxPath {
            get {
                return ResourceManager.GetString("Settings_ErxPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source data files (.cea):.
        /// </summary>
        public static string Settings_Folders {
            get {
                return ResourceManager.GetString("Settings_Folders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App language (requires a restart).
        /// </summary>
        public static string Settings_Language {
            get {
                return ResourceManager.GetString("Settings_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Selected.
        /// </summary>
        public static string Settings_RemoveSelected {
            get {
                return ResourceManager.GetString("Settings_RemoveSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save configuration.
        /// </summary>
        public static string Settings_Save {
            get {
                return ResourceManager.GetString("Settings_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Configuration.
        /// </summary>
        public static string Settings_Title {
            get {
                return ResourceManager.GetString("Settings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deselect All.
        /// </summary>
        public static string Watchlist_DeselectAll {
            get {
                return ResourceManager.GetString("Watchlist_DeselectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading quantities....
        /// </summary>
        public static string Watchlist_Loading {
            get {
                return ResourceManager.GetString("Watchlist_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search quantity:.
        /// </summary>
        public static string Watchlist_SearchContent {
            get {
                return ResourceManager.GetString("Watchlist_SearchContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All.
        /// </summary>
        public static string Watchlist_SelectAll {
            get {
                return ResourceManager.GetString("Watchlist_SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show selected only.
        /// </summary>
        public static string Watchlist_ShowSelected {
            get {
                return ResourceManager.GetString("Watchlist_ShowSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Watched Quantities.
        /// </summary>
        public static string Watchlist_Title {
            get {
                return ResourceManager.GetString("Watchlist_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Window_Close {
            get {
                return ResourceManager.GetString("Window_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting Started.
        /// </summary>
        public static string Window_GettingStarted_Title {
            get {
                return ResourceManager.GetString("Window_GettingStarted_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximize.
        /// </summary>
        public static string Window_Maximize {
            get {
                return ResourceManager.GetString("Window_Maximize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize.
        /// </summary>
        public static string Window_Minimize {
            get {
                return ResourceManager.GetString("Window_Minimize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore.
        /// </summary>
        public static string Window_Restore {
            get {
                return ResourceManager.GetString("Window_Restore", resourceCulture);
            }
        }
    }
}
